### ISSUE TITLE
ARM

### ISSUE THREAD

**Issue by TorHelper** [coldhakca/tor-relay-bootstrap#19]
Add "Arm" support?

The anonymizing relay monitor (arm) is a CLI status monitor for Tor. This functions much like top does for system usage, providing real time statistics for:

-Resource usage (bandwidth, cpu, and memory usage)
-General relaying information (nickname, fingerprint, flags, or/dir/controlports)
-Event log with optional regex filtering and deduplication
-Connections correlated against tor's consensus data (ip, connection types, relay details, etc)
-Torrc configuration file with syntax highlighting and validation

`apt-get install tor-arm`

**Comment by TorHelper** [comment]
Correction: I now see on line 29 that "tor-arm" is installed.

How about adding documentation of it and how to open the Tor Arm GUI? `sudo -u debian-tor arm`

**Comment by github-user-1** [comment]
The tor-arm tool is developed under the new name "nyx" in the meantime and this is the tool to be used (as arm has issues and therefor is replaced by nyx). Installation of nyx is currently via:

% git clone https://git.torproject.org/stem.git
% cd stem
% sudo python setup.py install
% cd ..
% git clone https://git.torproject.org/nyx.git
% cd nyx
% sudo python setup.py install

**Comment by Phoul** [comment]
We will wait for nyx to be considered stable before moving forward with this. Closing.
